### ISSUE TITLE
${server.base.url} like variable that returns IP address of server

### ISSUE THREAD

**Issue by ranasrule** [nroduit/weasis-pacs-connector#13]
In **dicom-dcm4chee.properties** file variable **${server.base.url}** returns the URL with IP and PORT but there is no way to get IP of server only.Using the variable **${server.host}** doesn't work.Kindly incorporate a way to fetch only IP using a variable like **${server.base.ip}**

**Comment by nroduit** [comment]
Add ${server.host}, see https://github.com/nroduit/weasis-pacs-connector/commit/b6798e2b382736a341c9b7af5cd9dc392fed923f
