### ISSUE TITLE
Ability to query more than one PACS server

### ISSUE THREAD

**Issue by alcir** [nroduit/weasis-pacs-connector#6]
It should be not so difficult to have the ability to query multiple PACS using a single installation of weasis-pacs-connector.

I managed to run weasis-pacs-connector inside Tomcat. It works as expected.
In order to query many pacs server, I have deployed many weasis-pacs-connector with different names, each with a weasis-connector-default.properties file inside it, like a webapp for each PACS server I need to query.
Something like this:

> /path/to/tomcat/webapps/weasis-pacs-connector-rx
> /path/to/tomcat/webapps/weasis-pacs-connector-mr

I'm not a developer, but looking at the source code it should not be too difficult to read more than a configuration file. For instance, in order to query a specific server and read a specific configuration file, we can add a new property in the URL, like for instance 
http://server:8080/weasis-pacs-connector/manifest?patientID=12345&**server**=PACS1 
or
http://server:8080/weasis-pacs-connector/manifest?patientID=6789&**server**=PACS2

So, looking at the server value we can read the related properties file containing pacsAET, pacsHost, pacsPort, wadoQueriesURL, etc.

**Comment by nroduit** [comment]
This is on-going development that will be in the next release.

It will be also possible to make a request to several PACS. That means the viewer will open images from different PACS with only one request.

**Comment by alcir** [comment]
This is awesome! Thanks.

**Comment by nroduit** [comment]
Implemented in weasis-pacs-connector 6
